export const SideProjects = [
  {
    id: 'Door accecc system',
    name: 'Door accecc system',
    topLine: 'Go/jQuery/Redis/Postman',
    headline: 'Door accecc system',
    descr: 'member management for co-working space',
    link: 'path or url',
    alt: 'Door accecc system imgage.',
    imgStart: true,
    lightBg: true,
    lightText: true,
    buttonLabel: 'Door accecc system',
  },
  {
    id: 'Portfolio',
    name: 'Portfolio',
    topLine: 'React/',
    headline: "Leah's Portfolio",
    descr:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias suscipit quasi ab harum natus, atis atque delectus! Doloremque quo nam laudantium tempore incidunt?',
    link: 'path or url',
    alt: 'Portfolio imgage.',
    imgStart: true,
    lightBg: true,
    lightText: true,
    buttonLabel: 'Portfolio',
  },
  {
    id: 'Template for practicing',
    name: 'Template for practicing',
    topLine: 'Go/jQuery/Redis/Postman',
    headline: 'Template for practicing',
    descr:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias suscipit quasi ab harum natus, mollitiais atque delectus! Doloremque quo nam laudantium tempore incidunt?',
    link: 'path or url',
    alt: 'Template for practicing imgage.',
    imgStart: false,
    lightBg: false,
    lightText: true,
    buttonLabel: 'Template for practicingy',
  },
  {
    id: 'Redesign McDonald',
    name: 'Redesign McDonald',
    topLine: 'HTMl/javaScript/CSS/Bootstrap',
    headline: 'Redesign McDonald',
    descr:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias suscipit quasi ab harum natus, mollitia explicabo reprehenderit sequi',
    link: 'path or url',
    alt: 'Redesign McDonald video.',
    imgStart: true,
    lightBg: true,
    lightText: true,
    buttonLabel: 'NoNo',
  },
  {
    id: 'Imitate Furniture Website',
    name: 'Imitate Furniture Website',
    topLine: 'HTMl/javaScript/CSS/Bootstrap',
    headline: 'Imitate Furniture Website',
    descr:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias suscipit quasi ab harum natus, mollitia explicabo reprehenderit sequi',
    link: 'path or url',
    alt: 'Imitate Furniture Website video.',
    imgStart: true,
    lightBg: true,
    lightText: true,
    buttonLabel: 'NoNo',
  },
];
