export const SideProjects = [
  {
    id: 'Project 1',
    name: 'Project 1',
    topLine: 'expense tracker',
    headline: 'The shining, everyday moment at Prada',
    descr:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias sio, eum sapiente? Illum et perspiciatis atque delectus! Doloremque quo nam laudantium tempore incidunt?',
    link: 'path or url',
    alt: 'Project 1 imgage.',
    imgStart: true,
    lightBg: true,
    lightText: true,
    buttonLabel: 'Start Today',
  },
  {
    id: 'Project 2',
    name: 'Project 2',
    topLine: 'to-do list',
    headline: 'The shining, everyday moment at Prada',
    descr:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias suscipit quasi ab harum natus, atis atque delectus! Doloremque quo nam laudantium tempore incidunt?',
    link: 'path or url',
    alt: 'Project 1 imgage.',
    imgStart: true,
    lightBg: true,
    lightText: true,
    buttonLabel: 'Start Today',
  },
  {
    id: 'Project 3',
    name: 'Project 3',
    topLine: 'hook-useRef',
    headline: 'The shining, everyday moment at Prada',
    descr:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias suscipit quasi ab harum natus, mollitiais atque delectus! Doloremque quo nam laudantium tempore incidunt?',
    link: 'path or url',
    alt: 'Project 3 imgage.',
    imgStart: false,
    lightBg: false,
    lightText: true,
    buttonLabel: 'Start Today',
  },
  {
    id: 'Project 4',
    name: 'Project 4',
    topLine: 'hook-useContent',
    headline: 'The shining, everyday moment at Prada',
    descr:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias suscipit quasi ab harum natus, mollitia explicabo reprehenderit sequi',
    link: 'path or url',
    alt: 'Project 1 imgage.',
    imgStart: true,
    lightBg: true,
    lightText: true,
    buttonLabel: 'Start Today',
  },
  {
    id: 'Project 5',
    name: 'Project 5',
    topLine: 'hook-useContent',
    headline: 'The shining, everyday moment at Prada',
    descr:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias suscipit quasi ab harum natus, mollitia explicabo reprehenderit sequi',
    link: 'path or url',
    alt: 'Project 1 imgage.',
    imgStart: true,
    lightBg: true,
    lightText: true,
    buttonLabel: 'Start Today',
  },
];
